### ISSUE TITLE
Cannot compute gradient of variance

### ISSUE THREAD

**Issue by Balandat** [jrg365/gpytorch#67]
First of all, this package looks really great.

I'd like to compute the gradient of the variance of a prediction, but this fails with 
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`.

To repro (here `model` is the trained/conditioned model from the simple_gp_regression.ipynb example):
```
>> test_x = Variable(torch.rand(10), requires_grad=True)
>> output = model(test_x)

# this works just fine
>> sum_of_means = output.mean().sum()
>> sum_of_means.backward()
>> test_x.grad
Variable containing:
 3.4206
-3.2818
 1.8668
 3.5644
-0.7677
 0.7666
 6.4394
 5.1365
-5.0451
 6.0161
[torch.FloatTensor of size 10]

# this fails with said error
>> sum_of_vars = output.var().sum()
>> sum_of_vars.backward()
>> test_x.grad
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-dad61ee95fc5> in <module>()
      1 sum_of_vars = output.var().sum()
----> 2 sum_of_vars.backward()
      3 test_x.grad

/data/users/balandat/fbsource/fbcode/buck-out/dev/gen/bento/kernels/bento_kernel_ae_dev#link-tree/torch/autograd/variable.py in backward(self, gradient, retain_graph, create_graph, retain_variables)
    165                 Variable.
    166         """
--> 167         torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
    168 
    169     def register_hook(self, hook):

/data/users/balandat/fbsource/fbcode/buck-out/dev/gen/bento/kernels/bento_kernel_ae_dev#link-tree/torch/autograd/__init__.py in backward(variables, grad_variables, retain_graph, create_graph, retain_variables)
     97 
     98     Variable._execution_engine.run_backward(
---> 99         variables, grad_variables, retain_graph)
    100 
    101 

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

I tried to track down where this happens, but didn't get very far (given the less than informative stack trace).

Computing the gradient of the variance would be really useful for using this package for bayesian optimization.

**Comment by gpleiss** [comment]
I think I know what the issue is, and it should be fixed on the `alpha_release` branch. We're holding off merging in that branch until all of the rest of our changes are in place (probably mid February).

In the meantime, I think you should also be able to fix this by setting `gpytorch.functions.fast_pred_var = False` at the top of the file.

(Also, feel free to try out the `alpha_release` branch, but be warned that it might be a bit buggy, and the interface has changed!)

Let me know if this works!

**Comment by Balandat** [comment]
So it appears `fast_pred_var = False` by default, and in particular this is the case also in my code. 

I'll look into trying the `alpha_release` branch.

**Comment by gpleiss** [comment]
Hmm, I think @jrg365 got BayesOpt to work with gradients at one point. I'll have him investigate this some more.

**Comment by Balandat** [comment]
I just tried this on the latest commit of alpha_release (525795adedc79bc77d5c61f238a10255b83078d2), issue persists

**Comment by gpleiss** [comment]
Okay... I'll investigate this more today.

**Comment by jrg365** [comment]
With de72a06, sum_of_vars.backward() now produces gradients for test_x as expected.

**Comment by Balandat** [comment]
great, thanks for the quick fix!
